install.packages("BiocManager")
BiocManager::install("ggtree",version=2.2)
BiocManager::install("microbiome",version=1.1)
BiocManager::install("aldex2",version=1.20)
install.packages("ape")
install.packages("useful")
install.packages("broom")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("pheatmap")2
install.packages("phytools")7
install.packages("plotly").1
install.packages("purrr")
install.packages("readr")
install.packages("stringr")
install.packages("tibble")
install.packages("tidyr")
install.packages("vegan")
install.packages("kableextra")
