---
title: "Draw Tree"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, 
                      warning = FALSE, cache = FALSE, include = TRUE)
knitr::opts_knit$set(root.dir = "..") # set root dir one level above where Rmd is saved
```

```{r libraries}
library(dplyr)
library(readr)
library(ggtree)
```

```{r read_newick}
T <- ggtree::read.tree("Example/genomes/tree/gtdbtk.bac120.nwk")
```

```{r tax_labels}
# generate tip labs; defaults to MAG name, switch to MAG annotation
Tax <- read_tsv("Example/Results/taxonomy.tsv") %>%
  mutate(Labels = ifelse(is.na(species) & is.na(genus), paste0(family, " ", user_genome), species)) %>%
  transmute(Labels = ifelse(is.na(Labels), paste0(genus, " ", user_genome), Labels), across(everything()))

# node names are stored in T$tip.label.
Tax <- Tax[order(match(Tax$user_genome, T$tip.label)), ] # sort Tax according to the tree
stopifnot(all.equal(Tax$user_genome, T$tip.label)) # make sure the sorting worked
T$tip.label <- Tax$Labels
```

```{r color_tree, fig.height=10}
# color tree by phylum
ggtree(T, layout = 'circular') %<+% Tax + 
  geom_tiplab(aes(color = phylum)) +
  theme(legend.position = "bottom")
```


```{r highlight_tree, fig.height = 10}
library(phytools)
Bacteroidota <- findMRCA(T, c("RC9 sp002298075", "Paramuribaculum MAG61"))

ggtree(T, layout = 'circular') +
  geom_tiplab() +
  geom_highlight(Bacteroidota, fill = "steelblue", extend = 3) 
```
